services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    command: ["mongod", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: leiferusr
      MONGO_INITDB_ROOT_PASSWORD: leiferpass
      MONGO_INITDB_DATABASE: leifer
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    # networks:
    #   - compose_default
  # Replica set - outdated.  Need this to watch/stream collections
  # mongodb_rs:
  #   image: mongo:6.0
  #   container_name: mongodb_rs
  #   command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data_rs:/data/db
  #     #- ./compose/mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro
  #   restart: unless-stopped
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: samples_user
      POSTGRES_PASSWORD: samplez
      POSTGRES_DB: samples_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/pgdata/data
    # networks:
    #   - compose_default
  # Vector support...not using
  # postgres:
  #   image: ankane/pgvector
  #   container_name: pgvector
  #   environment:
  #     POSTGRES_USER: samples_user
  #     POSTGRES_PASSWORD: samplez
  #     POSTGRES_DB: samples_db
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  weaviate:
    container_name: weaviate
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'

volumes:
  redis_data:
  mongodb_data:
  pgdata:
  weaviate_data: