services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongodb_rs:
    image: mongo:6.0
    container_name: mongodb_rs
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_rs:/data/db
    restart: unless-stopped

  postgres:
    image: ankane/pgvector
    container_name: datapilot-pgvector
    environment:
      POSTGRES_USER: datapilot
      POSTGRES_PASSWORD: pilot123
      POSTGRES_DB: datapilot_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'

volumes:
  reds_date:
  mongodb_data_rs:
    driver: local
  pgdata:
  weaviate_data: